// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {app} from '../models';

export function AnalyzePaths(arg1:Array<string>):Promise<Array<model.AnalysisResult>>;

export function GetConfig():Promise<app.AppConfigView>;

export function SaveAPIKeys(arg1:app.APIKeyInput):Promise<void>;

export function SelectEmailFiles():Promise<Array<model.AnalysisResult>>;

export function Version():Promise<string>;

export function Watermark():Promise<string>;
