// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzePaths(arg1) {
  return window['go']['app']['App']['AnalyzePaths'](arg1);
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function SaveAPIKeys(arg1) {
  return window['go']['app']['App']['SaveAPIKeys'](arg1);
}

export function SelectEmailFiles() {
  return window['go']['app']['App']['SelectEmailFiles']();
}

export function Version() {
  return window['go']['app']['App']['Version']();
}

export function Watermark() {
  return window['go']['app']['App']['Watermark']();
}
